/**
 * OmniRoute server lifecycle manager for Orca IDE.
 *
 * Locates the OmniRoute repo, runs bootstrap (npm install if missing),
 * spawns the dev server, health-polls it, and kills it on shutdown.
 * Unlike Baton: OmniRoute auto-starts on app ready with no user action.
 */
import { execSync, spawn, type ChildProcess } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { totalmem, homedir } from 'node:os'
import { app } from 'electron'

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

export type OmniRouteStatus =
  | 'idle'
  | 'setup'
  | 'bootstrapping'
  | 'starting'
  | 'running'
  | 'error'

export interface OmniRouteManagerState {
  status: OmniRouteStatus
  port: number | null
  pid: number | null
  error: string | null
  progress: string
}

export interface OmniRouteProcess {
  child: ChildProcess
  port: number
  pid: number
}

type StatusCallback = (state: OmniRouteManagerState) => void

/* ------------------------------------------------------------------ */
/* State                                                               */
/* ------------------------------------------------------------------ */

let serverProcess: OmniRouteProcess | null = null
let statusCallback: StatusCallback | null = null
let statusOverride: OmniRouteStatus | null = null
export const DEFAULT_PORT = 20128

/* ------------------------------------------------------------------ */
/* V8 heap calibration (~35% of RAM, clamped [512, 4096] MB)           */
/* ------------------------------------------------------------------ */

function calibrateHeapMb(): number {
  const totalMb = totalmem() / (1024 * 1024)
  if (!Number.isFinite(totalMb) || totalMb <= 0) return 512
  return Math.min(4096, Math.max(512, Math.floor(totalMb * 0.35)))
}

/* ------------------------------------------------------------------ */
/* Status reporting                                                    */
/* ------------------------------------------------------------------ */

function notifyStatus(state: OmniRouteManagerState): void {
  statusOverride = state.status
  statusCallback?.(state)
}

export function setStatusCallback(cb: StatusCallback | null): void {
  statusCallback = cb
}

export function getState(): OmniRouteManagerState {
  return {
    status: serverProcess ? 'running' : (statusOverride ?? 'idle'),
    port: serverProcess?.port ?? null,
    pid: serverProcess?.pid ?? null,
    error: null,
    progress: ''
  }
}

/* ------------------------------------------------------------------ */
/* Initial setup — detect & save INITIAL_PASSWORD                      */
/* ------------------------------------------------------------------ */

/** Resolve OmniRoute data directory (mirrors bootstrap-env.mjs logic). */
function resolveDataDir(): string {
  if (process.env.DATA_DIR?.trim()) return join(process.env.DATA_DIR.trim())
  if (process.platform === 'win32') {
    const appData = process.env.APPDATA || join(homedir(), 'AppData', 'Roaming')
    return join(appData, 'omniroute')
  }
  const xdg = process.env.XDG_CONFIG_HOME?.trim()
  if (xdg) return join(xdg, 'omniroute')
  return join(homedir(), '.omniroute')
}

function readEnvFile(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) return {}
  const env: Record<string, string> = {}
  const lines = readFileSync(filePath, 'utf8').split(/\r?\n/)
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx < 1) continue
    const key = trimmed.slice(0, eqIdx).trim()
    const raw = trimmed.slice(eqIdx + 1).trim()
    const val = raw.replace(/^["']|["']$/g, '')
    env[key] = val
  }
  return env
}

function writeEnvFile(filePath: string, env: Record<string, string>): void {
  mkdirSync(dirname(filePath), { recursive: true })
  const lines = [
    '# Auto-generated by OmniRoute bootstrap — do not delete',
    '',
    ...Object.entries(env).map(([k, v]) => `${k}=${v}`),
    ''
  ]
  writeFileSync(filePath, lines.join('\n'), 'utf8')
}

/** Returns true if a valid (non-default) INITIAL_PASSWORD is configured. */
export function isSetupComplete(repoDir?: string | null): boolean {
  // Check process.env first (highest priority per bootstrap-env)
  const processVal = process.env.INITIAL_PASSWORD
  if (processVal?.trim() && processVal.trim() !== 'CHANGEME') return true

  // Check server.env and DATA_DIR/.env
  const dataDir = resolveDataDir()
  for (const p of [join(dataDir, 'server.env'), join(dataDir, '.env')]) {
    const val = readEnvFile(p).INITIAL_PASSWORD
    if (val?.trim() && val.trim() !== 'CHANGEME') return true
  }

  // Check repo .env (OmniRoute's CWD is repoDir when running)
  if (repoDir) {
    const repoEnv = readEnvFile(join(repoDir, '.env'))
    const val = repoEnv.INITIAL_PASSWORD
    if (val?.trim() && val.trim() !== 'CHANGEME') return true
  }

  return false
}

/** Write INITIAL_PASSWORD to server.env and update process.env. */
export async function saveSetup(
  values: { initialPassword: string }
): Promise<{ ok: boolean; error?: string }> {
  const password = values.initialPassword?.trim()
  if (!password) return { ok: false, error: 'Admin password is required.' }
  if (password === 'CHANGEME') return { ok: false, error: 'Choose a password other than CHANGEME.' }

  try {
    const envPath = join(resolveDataDir(), 'server.env')
    const existing = readEnvFile(envPath)
    existing.INITIAL_PASSWORD = password
    writeEnvFile(envPath, existing)
    // Also set in process.env so any in-session re-start picks it up
    process.env.INITIAL_PASSWORD = password
    return { ok: true }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}

/* ------------------------------------------------------------------ */
/* OmniRoute repo resolution                                           */
/* ------------------------------------------------------------------ */

export async function getOmniRouteRepo(): Promise<string | null> {
  const envRepo = process.env.OMNIROUTE_REPO
  if (envRepo && existsSync(join(envRepo, 'scripts', 'dev', 'run-next.mjs'))) return envRepo

  const orcaAppPath = app.getAppPath()
  const candidates = [
    join(orcaAppPath, '..', 'OmniRoute'),
    'C:\\Users\\lenovo\\Desktop\\Gagan\\OmniRoute'
  ]

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'scripts', 'dev', 'run-next.mjs'))) return candidate
  }
  return null
}

/* ------------------------------------------------------------------ */
/* Bootstrap (first-run: npm install)                                  */
/* ------------------------------------------------------------------ */

export async function bootstrapOmniRoute(
  repoDir: string,
  onProgress: (line: string) => void
): Promise<void> {
  if (existsSync(join(repoDir, 'node_modules', '.package-lock.json'))) {
    onProgress('OmniRoute already installed — skipping bootstrap')
    return
  }

  notifyStatus({ status: 'bootstrapping', port: null, pid: null, error: null, progress: 'Installing OmniRoute dependencies...' })
  onProgress('Installing OmniRoute dependencies (first run, may take a minute)...')

  await runCommand('npm', ['install', '--no-audit', '--no-fund'], repoDir, onProgress)

  if (!existsSync(join(repoDir, 'node_modules', '.package-lock.json'))) {
    throw new Error('OmniRoute bootstrap failed — node_modules not created after npm install')
  }
  onProgress('OmniRoute bootstrap complete')
}

/* ------------------------------------------------------------------ */
/* Server start / stop                                                 */
/* ------------------------------------------------------------------ */

/** Kill orphaned OmniRoute process on the given port */
export function killOrphanedServer(port: number = DEFAULT_PORT): void {
  try {
    const lines = execSync(
      `netstat -ano | findstr :${port} | findstr LISTENING`,
      { encoding: 'utf8', windowsHide: true }
    )
    const match = lines.match(/(\d+)\s*$/m)
    if (match) {
      const pid = Number(match[1])
      if (pid > 0 && pid !== process.pid) {
        try { execSync(`taskkill /PID ${pid} /F`, { encoding: 'utf8', windowsHide: true }) } catch { /* already gone */ }
      }
    }
  } catch {
    // No listener on the port — nothing to kill
  }
}

export async function startServer(
  repoDir: string,
  port: number = DEFAULT_PORT
): Promise<OmniRouteProcess> {
  if (serverProcess) {
    await stopServer(serverProcess)
  }

  notifyStatus({ status: 'starting', port, pid: null, error: null, progress: 'Starting OmniRoute server...' })

  killOrphanedServer(port)

  const serverScript = join(repoDir, 'scripts', 'dev', 'run-next.mjs')
  const heapMb = calibrateHeapMb()

  // ELECTRON_RUN_AS_NODE makes the bundled Electron binary behave as plain Node.js.
  // Without it, a packaged .exe would try to boot a second Electron app instead of
  // running the server script. This is the same pattern Orca uses for daemon-entry,
  // plugin-host, and the CLI shim.
  const child = spawn(process.execPath, [serverScript, 'dev'], {
    cwd: repoDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: {
      ...process.env,
      ELECTRON_RUN_AS_NODE: '1',
      PORT: String(port),
      DASHBOARD_PORT: String(port),
      NODE_ENV: 'development',
      NODE_OPTIONS: `--max-old-space-size=${heapMb}`
    },
    detached: false,
    shell: false
  })

  const proc: OmniRouteProcess = { child, port, pid: child.pid ?? 0 }
  serverProcess = proc

  child.stdout?.on('data', (data: Buffer) => {
    const line = data.toString().trim()
    if (line) console.log(`[omniroute] ${line}`)
  })
  child.stderr?.on('data', (data: Buffer) => {
    const line = data.toString().trim()
    if (line) console.error(`[omniroute] ${line}`)
  })

  child.on('exit', (code) => {
    console.log(`[omniroute] exited with code ${code}`)
    serverProcess = null
    notifyStatus({ status: 'idle', port: null, pid: null, error: null, progress: '' })
  })

  child.on('error', (err) => {
    console.error(`[omniroute] spawn error:`, err.message)
    serverProcess = null
    notifyStatus({ status: 'error', port: null, pid: null, error: err.message, progress: '' })
  })

  // Health poll — wait for the server to respond (180s timeout, matching OmniRoute's own Electron launcher).
  // Bail early if the child exits (crash) instead of polling a dead port for the full timeout.
  await healthPoll(port, 180_000, () => serverProcess !== null)

  notifyStatus({ status: 'running', port, pid: proc.pid, error: null, progress: 'OmniRoute is running' })
  return proc
}

/**
 * Full start pipeline shared by auto-start (main process) and the IPC start
 * handler. Never throws — errors fold into state and are returned.
 */
export async function startOmniRoute(): Promise<{ ok: boolean; error?: string }> {
  if (serverProcess) return { ok: true }

  try {
    const repoDir = await getOmniRouteRepo()

    // Check initial setup before starting — show setup dialog if not configured
    if (!isSetupComplete(repoDir)) {
      notifyStatus({
        status: 'setup',
        port: null,
        pid: null,
        error: null,
        progress: 'OmniRoute initial setup required'
      })
      return { ok: false, error: 'OmniRoute setup required. Configure the admin password in the setup dialog.' }
    }

    if (!repoDir) {
      notifyStatus({
        status: 'error',
        port: null,
        pid: null,
        error: 'OmniRoute repo not found. Set OMNIROUTE_REPO env var or clone it next to Orca.',
        progress: ''
      })
      return { ok: false, error: 'OmniRoute repo not found. Set OMNIROUTE_REPO env var.' }
    }

    await bootstrapOmniRoute(repoDir, (line) => {
      notifyStatus({ status: 'bootstrapping', port: null, pid: null, error: null, progress: line })
    })

    const proc = await startServer(repoDir, DEFAULT_PORT)
    notifyStatus({ status: 'running', port: proc.port, pid: proc.pid, error: null, progress: 'OmniRoute is running' })
    return { ok: true }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    console.error(`[omniroute] start failed:`, message)
    notifyStatus({ status: 'error', port: null, pid: null, error: message, progress: '' })
    return { ok: false, error: message }
  }
}

export async function stopServer(proc: OmniRouteProcess): Promise<void> {
  return new Promise<void>((resolve) => {
    const { child } = proc
    if (!child || !child.pid) {
      serverProcess = null
      resolve()
      return
    }

    let resolved = false
    const done = () => {
      if (!resolved) { resolved = true; resolve() }
    }

    child.on('exit', done)
    child.on('error', done)

    // SIGTERM → graceful shutdown → SIGKILL after 5s
    try { child.kill('SIGTERM') } catch { /* already dead */ }
    setTimeout(() => {
      try { child.kill('SIGKILL') } catch { /* already dead */ }
      setTimeout(done, 2000)
    }, 5000)
  }).then(() => {
    serverProcess = null
    statusOverride = 'idle'
  })
}

export function killServerIfRunning(): void {
  if (serverProcess) {
    try { serverProcess.child.kill('SIGTERM') } catch { /* ignore */ }
    serverProcess = null
  }
  statusOverride = 'idle'
}

export async function stopServerIfRunning(): Promise<void> {
  if (serverProcess) {
    await stopServer(serverProcess)
  } else {
    statusOverride = 'idle'
  }
}

/* ------------------------------------------------------------------ */
/* Health poll                                                         */
/* ------------------------------------------------------------------ */

async function healthPoll(port: number, timeoutMs: number, isAlive?: () => boolean): Promise<void> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    if (isAlive && !isAlive()) {
      throw new Error(`OmniRoute server process exited before responding on port ${port}`)
    }
    try {
      const res = await fetch(`http://127.0.0.1:${port}/api/monitoring/health`, {
        signal: AbortSignal.timeout(3000)
      })
      if (res.ok) return
    } catch {
      // Not ready yet
    }
    await new Promise(r => setTimeout(r, 500))
  }
  throw new Error(`OmniRoute server did not respond within ${timeoutMs}ms on port ${port}`)
}

/* ------------------------------------------------------------------ */
/* Command runner                                                      */
/* ------------------------------------------------------------------ */

function runCommand(
  cmd: string,
  args: string[],
  cwd: string,
  onProgress: (line: string) => void
): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const child = spawn(cmd, args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, FORCE_COLOR: '0' },
      shell: false
    })

    child.stdout?.on('data', (data: Buffer) => {
      const line = data.toString().trim()
      if (line) onProgress(line)
    })
    child.stderr?.on('data', (data: Buffer) => {
      const line = data.toString().trim()
      if (line) onProgress(line)
    })

    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} ${args.join(' ')} exited with code ${code}`))
    })
    child.on('error', reject)
  })
}
